"""empty message

Revision ID: 098f6a054815
Revises: d967c14d9773
Create Date: 2023-08-28 12:57:46.951805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098f6a054815'
down_revision = 'd967c14d9773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
