"""create workout and messages tables

Revision ID: 237569d66944
Revises: 26681075375e
Create Date: 2023-08-24 15:31:38.291245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237569d66944'
down_revision = '26681075375e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workouts')
    op.drop_table('messages')
    # ### end Alembic commands ###
