"""empty message

Revision ID: 26681075375e
Revises: 79451f54fa69
Create Date: 2023-08-23 15:34:10.863058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26681075375e'
down_revision = '79451f54fa69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
